import { SearchOption } from '@/types/job';

export const COMMON_OPTIONS: SearchOption[] = [
  { flag: '--F', description: 'Directory containing .raw or .d files', type: 'path', required: true, category: 'common' },
  { flag: '--threads', description: 'Number of CPU threads (max 64)', type: 'number', required: true, defaultValue: '64', category: 'common' },
  { flag: '--verbose', description: 'Log detail level (0-4)', type: 'number', defaultValue: '1', category: 'common' },
  { flag: '--fasta-search', description: 'In silico digest', type: 'boolean', category: 'common' },
  { flag: '--qvalue', description: 'Precursor q-value threshold', type: 'number', defaultValue: '0.01', category: 'common' },
  { flag: '--out', description: 'Output report file path', type: 'path', required: true, category: 'common' },
  { flag: '--matrices', description: 'Output quantity matrices', type: 'boolean', category: 'common' },
  { flag: '--lib', description: 'Spectral library file', type: 'path', category: 'common' },
  { flag: '--gen-lib', description: 'Generate spectral library', type: 'boolean', category: 'common' },
  { flag: '--fasta', description: 'FASTA database file', type: 'path', category: 'common' },
  { flag: '--min-fr-mz', description: 'Min fragment m/z', type: 'number', defaultValue: '200', category: 'common' },
  { flag: '--max-fr-mz', description: 'Max fragment m/z', type: 'number', defaultValue: '1800', category: 'common' },
  { flag: '--met-excision', description: 'N-term methionine excision', type: 'boolean', category: 'common' },
  { flag: '--min-pep-len', description: 'Min peptide length', type: 'number', defaultValue: '7', category: 'common' },
  { flag: '--max-pep-len', description: 'Max peptide length', type: 'number', defaultValue: '30', category: 'common' },
  { flag: '--min-pr-mz', description: 'Min precursor m/z', type: 'number', defaultValue: '300', category: 'common' },
  { flag: '--max-pr-mz', description: 'Max precursor m/z', type: 'number', defaultValue: '1800', category: 'common' },
  { flag: '--min-pr-charge', description: 'Min precursor charge', type: 'number', defaultValue: '1', category: 'common' },
  { flag: '--max-pr-charge', description: 'Max precursor charge', type: 'number', defaultValue: '4', category: 'common' },
  { flag: '--cut', description: 'Cleavage specificity', type: 'string', defaultValue: 'K*,R*', category: 'common' },
  { flag: '--missed-cleavages', description: 'Max missed cleavages', type: 'number', defaultValue: '2', category: 'common' },
  { flag: '--unimod4', description: 'Unimod4 modifications', type: 'boolean', category: 'common' },
  { flag: '--var-mods', description: 'Max variable modifications', type: 'number', defaultValue: '1', category: 'common' },
  { flag: '--reanalyse', description: 'Enable MBR', type: 'boolean', category: 'common' },
  { flag: '--rt-profiling', description: 'ID, RT and IM profiling', type: 'boolean', category: 'common' },
];

export const OTHER_OPTIONS: SearchOption[] = [
  { "flag": "--cont-quant-exclude", "description": "peptides corresponding to protein sequence ids tagged with the specified tag will be excluded from normalisation as well as quantification of protein groups that do not include proteins with the tag", "type": "string", "category": "other" },
  { "flag": "--convert", "description": "makes DIA-NN convert the mass spec files to the .dia format. The files are either saved to the same location as the input files, or in the Temp/.dia dir, if it is specified (in the GUI or using the --out-dir option)", "type": "boolean", "category": "other" },
  { "flag": "--cut", "description": "specifies cleavage specificity for the in silico digest. Cleavage sites (pairs of amino acids) are listed separated by commas, '\\*' indicates any amino acid, and '!' indicates that the respective site will not be cleaved. Examples: \"--cut K\\*,R\\*,!*P\" &ndash; canonical tryptic specificity, \"--cut \" &ndash; digest disabled, \"--cut ** --missed-cleavages 100\" will make DIA-NN perform a non-specific digest (first do this for a single peptide length, to estimate the numbers of precursors generated)", "type": "string", "category": "other" },
  { "flag": "--dda", "description": "process data as DDA &ndash; must be used with DDA data, must not be used with DIA data", "type": "boolean", "category": "other" },
  { "flag": "--decoy-channel", "description": "specifies the decoy channel masses, wherein [channel] has the same syntax as for --channels", "type": "string", "category": "other" },
  { "flag": "--dg-keep-nterm", "description": "do not change the first N residues when generating decoys, default N = 1 ", "type": "number", "category": "other" },
  { "flag": "--dg-keep-cterm", "description": "do not change the last N residues when generating decoys, default N = 1 ", "type": "number", "category": "other" },
  { "flag": "--dg-min-shuffle", "description": "aim for any fragment mass shift introduced by shuffling during decoy generation to exceed X in absolute value, default 5.0", "type": "number", "category": "other" },
  { "flag": "--dg-min-mut", "description": "aim for the precursor mass shift during mutation during decoy generation to be at least X in absolute value, default 15.0", "type": "number", "category": "other" },
  { "flag": "--dg-max-mut", "description": "aim for the precursor mass shift during mutation during decoy generation not to exceed X in absolute value, default 50.0", "type": "number", "category": "other" },
  { "flag": "--dir", "description": "specifies a folder containing raw files to be processed. All files in the folder must be in .raw, .wiff, .mzML or .dia format", "type": "path", "category": "other" },
  { "flag": "--dir-all", "description": "as --dir, but recursive over subfolders", "type": "path", "category": "other" },
  { "flag": "--direct-quant", "description": "disable QuantUMS and use legacy DIA-NN quantification algorithms instead, also disables channel-specific protein quantification when analysing multiplexed samples", "type": "boolean", "category": "other" },
  { "flag": "--dl-no-fr", "description": "when using the deep learning predictor, prediction of fragment intensities will not be performed", "type": "boolean", "category": "other" },
  { "flag": "--dl-no-im", "description": "when using the deep learning predictor, prediction of ion mobilities will not be performed", "type": "boolean", "category": "other" },
  { "flag": "--dl-no-rt", "description": "when using the deep learning predictor, prediction of retention times will not be performed", "type": "boolean", "category": "other" },
  { "flag": "--duplicate-proteins", "description": "instructs DIA-NN not to skip entries in the sequence database with duplicate IDs (while by default if several entries have the same protein ID, all but the first entry will be skipped)", "type": "boolean", "category": "other" },
  { "flag": "--export-quant", "description": "add fragment quantities, fragment IDs and quality information to the .parquet output report", "type": "boolean", "category": "other" },
  { "flag": "--ext", "description": "adds a string to the end of each file name (specified with --f)", "type": "string", "category": "other" },
  { "flag": "--f", "description": "specifies a run to be analysed, use multiple --f commands to specify multiple runs", "type": "path", "category": "other" },
  { "flag": "--fasta-filter", "description": "only consider peptides matching the stripped sequences specified in the text file provided (one sequence per line), when processing a sequence database", "type": "path", "category": "other" },
  { "flag": "--fix-scoring", "description": "DIA-NN will not auto-adjust the Scoring setting depending on the search stage; currently, in DDA mode, during second MBR pass or when analysing with empirical library, DIA-NN may auto-switch to Proteoforms regardless of the initial Scoring setting", "type": "boolean", "category": "other" },
  { "flag": "--fixed-loss", "description": "instructs DIA-NN to apply a neutral loss (i.e. subtract the specified mass) to each fragment ion containing the specified modification(s) on the specified sites, proportional to the number of such sites within the fragment; this functionality is highly experimental and untested, there should be no more than one --fixed-loss or --var-loss declaration  ", "type": "string", "category": "other" },
  { "flag": "--fixed-mod", "description": "Adds the modification name to the list of recognised names and specifies the modification as fixed. Same syntax as for --var-mod. Has an effect of (i) applying fixed modifications during FASTA digest or (ii) declaring fixed modifications that can be applied to a library with --lib-fixed-mod", "type": "string", "category": "other" },
  { "flag": "--force-ms2", "description": "always require MS/MS evidence for precursor identification", "type": "boolean", "category": "other" },
  { "flag": "--force-swissprot", "description": "only consider SwissProt (i.e. marked with '>sp|') sequences when processing a sequence database", "type": "boolean", "category": "other" },
  { "flag": "--fr-model", "description": "specifies the file containing the fragmentation deep learning prediction model", "type": "path", "category": "other" },
  { "flag": "--full-profiling", "description": "enable using empirical spectra for empirical library generation", "type": "boolean", "category": "other" },
  { "flag": "--full-unimod", "description": "loads the complete UniMod modification database and disables the automatic conversion of modification names to the UniMod format", "type": "boolean", "category": "other" },
  { "flag": "--gen-spec-lib", "description": "instructs DIA-NN to generate a spectral library", "type": "boolean", "category": "other" },
  { "flag": "--global-norm", "description": "instructs DIA-NN to use simple global normalisation instead of RT-dependent normalisation", "type": "boolean", "category": "other" },
  { "flag": "--high-acc", "description": "QuantUMS settings will be optimised for maximum accuracy, i.e. to minimise any ratio compression quantitative bias", "type": "boolean", "category": "other" },
  { "flag": "--ids-to-names", "description": "protein sequence ids will also be used as protein names and genes, any information on actual protein names or genes will be ignored", "type": "boolean", "category": "other" },
  { "flag": "--id-profiling", "description": "set the empirical library generation mode to IDs profiling", "type": "boolean", "category": "other" },
  { "flag": "--ignore-decoys", "description": "ignore decoys when loading a .parquet library  ", "type": "boolean", "category": "other" },
  { "flag": "--ignore-pep", "description": "DIA-NN will not moderate q-values based on PEP values; use this to evaluate the accuracy of 'raw' DIA-NN q-value calculation against known ground truth; cf. --kb, --no-refine-q", "type": "boolean", "category": "other" },
  { "flag": "--il-eq", "description": "when using the 'Reannotate' function, peptides will be matched to proteins while considering isoleucine and leucine equivalent", "type": "boolean", "category": "other" },
  { "flag": "--im-acc", "description": "a parameter that should roughly correspond to the magnitude of observed IM value differences between different ion species matching the same precursor, default X = 0.02", "type": "number", "category": "other" },
  { "flag": "--im-model", "description": "specifies the file containing the IM deep learning prediction model", "type": "path", "category": "other" },
  { "flag": "--im-prec", "description": "a parameter that should roughly correspond to the magnitude of IM errors due to noise, default X = 0.01", "type": "number", "category": "other" },
  { "flag": "--im-window", "description": "IM extraction window will not be less than the specified value", "type": "number", "category": "other" },
  { "flag": "--im-window-mul", "description": "affects the IM window/tolerance, larger values result in larger IM extraction window, default X = 2.0", "type": "number", "category": "other" },
  { "flag": "--individual-mass-acc", "description": "mass accuracies, if set to automatic, will be determined independently for different runs", "type": "boolean", "category": "other" },
  { "flag": "--individual-reports", "description": "a separate output report will be created for each run", "type": "boolean", "category": "other" },
  { "flag": "--individual-windows", "description": "scan window, if set to automatic, will be determined independently for different runs", "type": "boolean", "category": "other" },
  { "flag": "--int-removal 0", "description": "disables the removal of interfering precursors, not recommended", "type": "boolean", "category": "other" },
  { "flag": "--kb", "description": "(Enterprise only) enable knowledge base &ndash; use data obtained from other datasets to boost identification numbers", "type": "boolean", "category": "other" },
  { "flag": "--lib-filter-pgq", "description": "apply a PG q-value filter when loading a .parquet library, do not use this unless FDR is independently controlled via entrapment", "type": "number", "category": "other" },
  { "flag": "--lib-fixed-mod", "description": "in silico applies a modification, previously declared using --fixed-mod, to a spectral library", "type": "string", "category": "other" },
  { "flag": "--light-models", "description": "use the built-in lightweight deep learning models for fragmentation, RT and IM prediction, these allow for an order of magnitude faster prediction with minimal quality loss", "type": "boolean", "category": "other" },
  { "flag": "--loc-factor", "description": "a factor affecting reported PTM localisation confidence, higher values result in higher confidence reported, default X = 40.0, valid range: 2.0 to 1000.0", "type": "number", "category": "other" },
  { "flag": "--loc-no-h3po4", "description": "DIA-NN will not generate fragments with H3PO4 losses to localise phosphosites ", "type": "boolean", "category": "other" },
  { "flag": "--mass-acc", "description": "sets the MS2 mass accuracy to N ppm", "type": "number", "category": "other" },
  { "flag": "--mass-acc-cal", "description": "sets the mass accuracy used during the calibration phase of the search to N ppm (default is 100 ppm, which is adjusted automatically to lower values based on the data)", "type": "number", "category": "other" },
  { "flag": "--mass-acc-ms1", "description": "sets the MS1 mass accuracy to N ppm", "type": "number", "category": "other" },
  { "flag": "--matrix-qvalue", "description": "sets the q-value used to filter the output matrices", "type": "number", "category": "other" },
  { "flag": "--matrix-spec-q", "description": "run-specific protein q-value filtering will be used, in addition to the global q-value filtering, when saving protein matrices. The ability to filter based on run-specific protein q-values, which allows to generate highly reliable data, is one of the advantages of DIA-NN", "type": "number", "category": "other" },
  { "flag": "--max-pr-charge", "description": "sets the maximum precursor charge for the in silico library generation or library-free search", "type": "number", "category": "other" },
  { "flag": "--mbr-fix-settings", "description": "when using the 'Unrelated runs' option in combination with MBR, the same settings will be used to process all runs during the second MBR pass", "type": "boolean", "category": "other" },
  { "flag": "--min-cal", "description": "provide a guidance to DIA-NN suggesting the minimum number of IDs to use for mass calibration", "type": "number", "category": "other" },
  { "flag": "--min-class", "description": "provide a guidance to DIA-NN suggesting the minimum number of IDs to use for linear classifier training", "type": "number", "category": "other" },
  { "flag": "--min-corr", "description": "forces DIA-NN to only consider peak group candidates with correlation scores at least X", "type": "number", "category": "other" },
  { "flag": "--min-fr", "description": "specifies the minimum number of fragments per precursors in the spectral library being saved", "type": "number", "category": "other" },
  { "flag": "--min-fr-aas", "description": "library will be filtered to only retain fragments comprising at least N residues, default N = 3", "type": "number", "category": "other" },
  { "flag": "--min-iso-win", "description": "filter out MS/MS isolation windows smaller than X, use this setting for Hybrid-DIA", "type": "number", "category": "other" },
  { "flag": "--max-iso-win", "description": "filter out MS/MS isolation windows larger than X, use this setting for Hybrid-DIA", "type": "number", "category": "other" },
  { "flag": "--min-peak", "description": "sets the minimum peak height to consider. Must be 0.01 or greater", "type": "number", "category": "other" },
  { "flag": "--min-pr-charge", "description": "sets the minimum precursor charge for the in silico library generation or library-free search", "type": "number", "category": "other" },
  { "flag": "--missed-cleavages", "description": "sets the maximum number of missed cleavages", "type": "number", "category": "other" },
  { "flag": "--mod", "description": "declares a modification name. Examples: \"--mod UniMod:5,43.005814\", \"--mod SILAC-Lys8,8.014199,label\"", "type": "string", "category": "other" },
  { "flag": "--no-batch-mode", "description": "disable batch mode, consequently, use all precursors for calibration", "type": "boolean", "category": "other" },
  { "flag": "--no-calibration", "description": "disables mass calibration, not recommended", "type": "boolean", "category": "other" },
  { "flag": "--no-cut-after-mod", "description": "discard peptides generated via in silico cuts after residues bearing a particular variable modification", "type": "string", "category": "other" },
  { "flag": "--no-decoy-channel", "description": "disables the use of a decoy channel for channel q-value calculation", "type": "boolean", "category": "other" },
  { "flag": "--no-fragmentation", "description": "DIA-NN will not consider fragments other than included in the spectral library", "type": "boolean", "category": "other" },
  { "flag": "--no-fr-selection", "description": "the selection of fragments for quantification based on the quality assessment of the respective extracted chromatograms will be disabled", "type": "boolean", "category": "other" },
  { "flag": "--no-isotopes", "description": "do not extract chromatograms for heavy isotopologues", "type": "boolean", "category": "other" },
  { "flag": "--no-lib-filter", "description": "the input library will be used 'as is' without discarding fragments that might be harmful for the analysis; use with caution", "type": "boolean", "category": "other" },
  { "flag": "--no-maxlfq", "description": "disables MaxLFQ for protein quantification", "type": "boolean", "category": "other" },
  { "flag": "--no-ms1", "description": "do not consider MS1 data, use only during method optimisation to evaluate the impact of MS1 on the data quality", "type": "boolean", "category": "other" },
  { "flag": "--no-norm", "description": "disables cross-run normalisation", "type": "boolean", "category": "other" },
  { "flag": "--no-peptidoforms", "description": "disables automatic activation of peptidoform scoring when variable modifications are declared, not recommended", "type": "boolean", "category": "other" },
  { "flag": "--no-prot-inf", "description": "disables protein inference (that is protein grouping) &ndash; protein groups from the spectral library will be used instead", "type": "boolean", "category": "other" },
  { "flag": "--no-prot-norm", "description": "disable protein-level normalisation", "type": "boolean", "category": "other" },
  { "flag": "--no-quant-files", "description": "instructs DIA-NN not to save .quant files to disk and store them in memory instead", "type": "boolean", "category": "other" },
  { "flag": "--no-refine-q", "description": "do not use protein information when calculating precursor q-values, essential if the goal is validation of DIA-NN's precursor-level q-values using classic entrapment  ", "type": "boolean", "category": "other" },
  { "flag": "--no-rt-norm", "description": "disable RT-dependent normalisation", "type": "boolean", "category": "other" },
  { "flag": "--no-rt-window", "description": "disables RT-windowed search", "type": "boolean", "category": "other" },
  { "flag": "--no-skyline", "description": "do not generate .skyline.speclib", "type": "boolean", "category": "other" },
  { "flag": "--no-stats", "description": "disables the generation of the stats file", "type": "boolean", "category": "other" },
  { "flag": "--no-swissprot", "description": "instruct bit DIA-NN not to give preference for SwissProt proteins when inferring protein groups", "type": "boolean", "category": "other" },
  { "flag": "--no-tims-scan", "description": "force processing of timsTOF .d acquisitions as dia-PASEF (i.e. not slice/diagonal), use this to process 'dia-PASEF' files that are wrongly recognised as Slice-PASEF by DIA-NN &ndash; this may happen e.g. if the files that have a single window within the frame split in several windows with identical m/z bounds but different IM ranges (not recommended)  ", "type": "boolean", "category": "other" },
  { "flag": "--original-mods", "description": "disables the automatic conversion of known modifications to the UniMod format names known to DIA-NN", "type": "boolean", "category": "other" },
  { "flag": "--out-dir", "description": "specifies the output directory for raw data conversion to .dia", "type": "path", "category": "other" },
  { "flag": "--out-lib", "description": "specifies the name of a spectral library to be generated", "type": "path", "category": "other" },
  { "flag": "--out-lib-copy", "description": "copies the spectral library used into the output folder", "type": "boolean", "category": "other" },
  { "flag": "--out-lib-qvalue", "description": "global precursor q-value threshold for empirical library generation, default value is 0.05 ", "type": "number", "category": "other" },
  { "flag": "--parent", "description": "override auto-detected DIA-NN folder path, where DIA-NN will look for deep learning models in models/ subfolder", "type": "path", "category": "other" },
  { "flag": "--peak-boundary", "description": "if the fragment or MS1 signal decays below its max / X, this is considered the boundary of the elution peak, affects among other algorithms the calculation of start/stop RT values reported in the main .parquet report", "type": "number", "category": "other" },
  { "flag": "--peak-translation", "description": "instructs DIA-NN to take advantage of the co-elution of isotopologues, when identifying and quantifying precursors; automatically activated when using --channels", "type": "boolean", "category": "other" },
  { "flag": "--peptidoforms", "description": "enables peptidoform confidence scoring", "type": "boolean", "category": "other" },
  { "flag": "--pg-level", "description": "controls the protein inference mode, with 0 &ndash; isoforms, 1 &ndash; protein names (as in UniProt), 2 &ndash; genes", "type": "number", "category": "other" },
  { "flag": "--pre-filter", "description": "use InfinDIA spectra representation to filter precursors during calibration stage of the conventional search", "type": "boolean", "category": "other" },
  { "flag": "--pre-search", "description": "use InfinDIA pre-search", "type": "boolean", "category": "other" },
  { "flag": "--pre-select", "description": "InfinDIA will aim to pre-select at least N precursors", "type": "number", "category": "other" },
  { "flag": "--pre-select-force", "description": "InfinDIA will aim not to exceed significantly the number set by --pre-select", "type": "boolean", "category": "other" },
  { "flag": "--predict-n-frag", "description": "specifies the maximum number of fragments predicted by the deep learning predictor, default value is 12", "type": "number", "category": "other" },
  { "flag": "--predictor", "description": "instructs DIA-NN to perform deep learning-based prediction of spectra, retention times and ion mobility values", "type": "boolean", "category": "other" },
  { "flag": "--prefix", "description": "adds a string at the beginning of each file name (specified with --f) &ndash; convenient when working with automatic scripts for the generation of config files", "type": "string", "category": "other" },
  { "flag": "--prosit", "description": "export prosit input based on the FASTA digest", "type": "boolean", "category": "other" },
  { "flag": "--proteoforms", "description": "enables the proteoform confidence scoring mode", "type": "boolean", "category": "other" },
  { "flag": "--pr-filter", "description": "specify a file containing a list of precursors (same format as the Precursor.Id column in DIA-NN output), FASTA digest will be filtered to only include these precursors", "type": "path", "category": "other" },
  { "flag": "--quant-acc", "description": "sets the precision-accuracy balance for QuantUMS to X, where X must be between 0 and 1", "type": "number", "category": "other" },
  { "flag": "--quant-pep", "description": "sets the posterior error probability threshold for precursor ions to be used for quantification: precursors not passing the threshold may be ignored by some algorithms of DIA-NN, default value is 0.05  ", "type": "number", "category": "other" },
  { "flag": "--quant-ori-names", "description": ".quant files will retain original raw file names even if saved to a separate directory, convenient for .quant file manipulation", "type": "boolean", "category": "other" },
  { "flag": "--quant-fr", "description": "sets the number of top fragment ions among which the fragments that will be used for quantification are chosen for the legacy (pre-QuantUMS) quantification mode. Default value is 6", "type": "number", "category": "other" },
  { "flag": "--quick-mass-acc", "description": "(experimental) when choosing the MS2 mass accuracy setting automatically, DIA-NN will use a fast heuristical algorithm instead of IDs number optimisation", "type": "boolean", "category": "other" },
  { "flag": "--quant-no-ms1", "description": "instructs QuantUMS not to use the recorded MS1 quantities directly", "type": "boolean", "category": "other" },
  { "flag": "--quant-params", "description": "use previously obtained QuantUMS parameters", "type": "string", "category": "other" },
  { "flag": "--quant-sel-runs", "description": "instructs QuantUMS to train its parameters on N automatically chosen runs, to speed up training for large experiments, N here must be 6 or greater", "type": "number", "category": "other" },
  { "flag": "--quant-tims-sum", "description": "for slice/scanning timsTOF methods, calculate intensities by taking the sum of all cognate signals across the cycle, as opposed to taking the maximum, use this for Synchro-PASEF", "type": "boolean", "category": "other" },
  { "flag": "--quant-train-runs", "description": "instructs QuantUMS to train its parameters on runs with indices in the range N1 to N2 (inclusive), e.g. --quant-train-runs 0:5 will perform training on 6 runs with indices 0 to 5", "type": "string", "category": "other" },
  { "flag": "--read-threads", "description": "use a particular number of CPU threads when reading raw files ", "type": "number", "category": "other" },
  { "flag": "--reanalyse", "description": "enables MBR", "type": "boolean", "category": "other" },
  { "flag": "--reannotate", "description": "reannotate the spectral library with protein information from the FASTA database, using the specified digest specificity", "type": "boolean", "category": "other" },
  { "flag": "--ref", "description": "specify a special (small) spectral library which will be used exclusively for calibration, same as the **Calibration lib** GUI option", "type": "path", "category": "other" },
  { "flag": "--regular-swath", "description": "all runs will be analysed as if they were not Scanning SWATH runs", "type": "boolean", "category": "other" },
  { "flag": "--report-decoys", "description": "save decoy PSMs to the main .parquet report", "type": "boolean", "category": "other" },
  { "flag": "--report-file-name", "description": "save the full run name, including the file path, to the main report  ", "type": "boolean", "category": "other" },
  { "flag": "--restrict-fr", "description": "some fragments will not be used for quantification, based on the value in the ExcludeFromAssay spectral library column; marking all fragments of a precursor as excluded will, together with --restrict-fr, suppress the use of this precursor for protein quantification whenever possible", "type": "boolean", "category": "other" },
  { "flag": "--rt-model", "description": "specifies the file containing the RT deep learning prediction model", "type": "path", "category": "other" },
  { "flag": "--rt-profiling", "description": "set the empirical library generation mode to IDs, RT and IM profiling", "type": "boolean", "category": "other" },
  { "flag": "--rt-window", "description": "RT extraction window will not be less than the specified value", "type": "number", "category": "other" },
  { "flag": "--rt-window-factor", "description": "Affects the RT extraction window, set to higher values to enable narrow RT windows, default N = 40", "type": "number", "category": "other" },
  { "flag": "--rt-window-force", "description": "RT extraction window will be set to the specified value", "type": "number", "category": "other" },
  { "flag": "--rt-window-mul", "description": "Affects the RT extraction window, larger values result in larger window, decrease for faster analysis, default X = 2.5", "type": "number", "category": "other" },
  { "flag": "--scanning-swath", "description": "all runs will be analysed as if they were Scanning SWATH runs", "type": "boolean", "category": "other" },
  { "flag": "--semi", "description": "when using the 'Reannotate' function, a peptide will be matched to a protein also if it could be obtained with one specific and one non-specific cut (at either of the termini)", "type": "boolean", "category": "other" },
  { "flag": "--sig-norm", "description": "enable signal-dependent normalisation, not recommended", "type": "boolean", "category": "other" },
  { "flag": "--site-ms1-quant", "description": "use MS1 quantities for modification site quantification matrices", "type": "boolean", "category": "other" },
  { "flag": "--skip-unknown-mods", "description": "instructs DIA-NN to ignore peptides with modifications that are not supported by the deep learning predictor, when performing the prediction", "type": "boolean", "category": "other" },
  { "flag": "--smart-profiling", "description": "enables an intelligent algorithm which determines how to extract spectra, when creating a spectral library from DIA data, use with --full-profiling. The performance has so far always been observed to be comparable to IDs, RT and IM profiling", "type": "boolean", "category": "other" },
  { "flag": "--species-genes", "description": "instructs DIA-NN to add the organism identifier to the gene names &ndash; useful for distinguishing genes from different species, when analysing mixed samples. Works with UniProt sequence databases.", "type": "boolean", "category": "other" },
  { "flag": "--species-ids", "description": "instructs DIA-NN to add the organism identifier to the sequence ids/protein isoform ids &ndash; useful for distinguishing protein ids from different species, when analysing mixed samples. Works with UniProt sequence databases.", "type": "boolean", "category": "other" },
  { "flag": "--sptxt-acc", "description": "sets the fragment filtering mass accuracy (in ppm) when reading .sptxt/.msp libraries", "type": "number", "category": "other" },
  { "flag": "--tag-to-ids", "description": "proteins that have the respective FASTA header start with tag (i.e. the string following '>' starts with tag) will have the tag incorporated in the respective protein sequence ids, names and genes", "type": "string", "category": "other" },
  { "flag": "--temp", "description": "specifies the Temp directory", "type": "path", "category": "other" },
  { "flag": "--time-corr-only", "description": "restrict machine learning during calibration", "type": "boolean", "category": "other" },
  { "flag": "--time-corr-only-force", "description": "restrict the use of machine learning for peak group selection during all search stages", "type": "boolean", "category": "other" },
  { "flag": "--tims-min-cnt", "description": "specifies the minimum number of peaks to constitute a centroided peak when loading timsTOF data  ", "type": "number", "category": "other" },
  { "flag": "--tims-min-int", "description": "specifies the minimum peak intensity (an integer ion count) to be considered when loading timsTOF data  ", "type": "number", "category": "other" },
  { "flag": "--tims-ms1-cycle", "description": "merge the MS/MS spectra from N consecutive cycles, each cycle defined as the set of MS/MS scans following an MS1 scan, use this option only for slice/scanning timsTOF data and always test if the performance is better than without it", "type": "number", "category": "other" },
  { "flag": "--tokens", "description": "specify the file name for the text file that contains a mapping between modified residues or N-term modifications and integers in the range 0-255, this file is used by the deep learning predictor", "type": "path", "category": "other" },
  { "flag": "--top", "description": "set N for the Top N protein quantification, default N = 1", "type": "number", "category": "other" },
  { "flag": "--tune-fr", "description": "tune the fragmentation deep learning predictor, requires --tune-lib. Fragmentation tuning can be detrimental, hence it is recommended to always compare the performance to the base fragmentation model", "type": "boolean", "category": "other" },
  { "flag": "--tune-im", "description": "tune the IM deep learning predictor, requires --tune-lib", "type": "boolean", "category": "other" },
  { "flag": "--tune-level", "description": "limit fine-tuning to a specific distillation level (N=0,1,2)", "type": "number", "category": "other" },
  { "flag": "--tune-lib", "description": "specifies the library to be used for deep learning predictor fine-tuning, may require declaring unknown modifications with --mod", "type": "path", "category": "other" },
  { "flag": "--tune-lr", "description": "specifies fine-tuning learning rate, default is 0.0005", "type": "number", "category": "other" },
  { "flag": "--tune-restrict-layers", "description": "keep RNN layer weights and embedding weights for all AAs except cysteine fixed when fine-tuning", "type": "boolean", "category": "other" },
  { "flag": "--tune-rt", "description": "tune the RT deep learning predictor, requires --tune-lib", "type": "boolean", "category": "other" },
  { "flag": "--use-quant", "description": "use existing .quant files, if available", "type": "boolean", "category": "other" },
  { "flag": "--var-combinations", "description": "if the number of modified peptides reaches N at K sites occupied for a particular sequence, occupancies greater than K will not be considered, default N = 1024. This setting limits unreasonable search space expansion due to peptides with too high numbers of variable modification sites", "type": "number", "category": "other" },
  { "flag": "--var-mods", "description": "sets the maximum number of variable modifications, see also --var-combinations", "type": "boolean", "category": "other" },
  { "flag": "--xic", "description": "instructs DIA-NN to extract MS1/fragment chromatograms for identified precursors within X seconds from the elution apex, with X set to 10s if not provided; the chromatograms are saved in .parquet files (one per run) located in a folder that is created in the same location as the main output report; equivalent to the 'XICs' option in the GUI", "type": "string", "category": "other" },
  { "flag": "--xic-theoretical-fr", "description": "makes DIA-NN extract chromatograms for all theoretical charge 1-2 fragment ions, including those with common neutral losses, if --xic is used", "type": "boolean", "category": "other" },
  { "flag": "--window", "description": "sets the scan window radius to a specific value. Ideally, should be approximately equal to the average number of MS/MS data points per peak", "type": "number", "category": "other" }
];

export const DIANN_OPTIONS = [...COMMON_OPTIONS, ...OTHER_OPTIONS.filter(o => !COMMON_OPTIONS.find(c => c.flag === o.flag))];
