import { SearchOption } from '@/types/job';

export const DIANN_OPTIONS: SearchOption[] = [
  { flag: '--F', type: 'path', description: 'Dir where all raw files will be expanded to --f params', required: true },
  { flag: '--out', type: 'path', description: 'Output file path', required: true },
  { flag: '--threads', type: 'number', description: 'Number of threads' },
  { flag: '--verbose', type: 'number', description: 'Verbosity level' },
  { flag: '--fasta-search', type: 'boolean', description: 'Perform FASTA search' },
  { flag: '--qvalue', type: 'number', description: 'Q-value threshold' },
  { flag: '--matrices', type: 'boolean', description: 'Generate matrices' },
  { flag: '--lib', type: 'path', description: 'Library path' },
  { flag: '--gen-lib', type: 'boolean', description: 'Generate library' },
  { flag: '--fasta', type: 'path', description: 'FASTA file path' },
  { flag: '--min-fr-mz', type: 'number', description: 'Min fragment m/z' },
  { flag: '--max-fr-mz', type: 'number', description: 'Max fragment m/z' },
  { flag: '--met-excision', type: 'boolean', description: 'Met excision' },
  { flag: '--min-pep-len', type: 'number', description: 'Min peptide length' },
  { flag: '--max-pep-len', type: 'number', description: 'Max peptide length' },
  { flag: '--min-pr-mz', type: 'number', description: 'Min precursor m/z' },
  { flag: '--max-pr-mz', type: 'number', description: 'Max precursor m/z' },
  { flag: '--min-pr-charge', type: 'number', description: 'Min precursor charge' },
  { flag: '--max-pr-charge', type: 'number', description: 'Max precursor charge' },
  { flag: '--cut', type: 'string', description: 'Cleavage rules' },
  { flag: '--missed-cleavages', type: 'number', description: 'Missed cleavages' },
  { flag: '--unimod4', type: 'boolean', description: 'Unimod4' },
  { flag: '--var-mods', type: 'number', description: 'Variable modifications' },
  { flag: '--reanalyse', type: 'boolean', description: 'Reanalyse' },
  { flag: '--rt-profiling', type: 'boolean', description: 'RT profiling' },
];
